feat(golang): support golang
netless-io/netless-token pull request #3
Opened 2020-09-01 09:00 UTC by BlackHole1

2020-09-01 09:17 UTC, Moskize91 requested changes

2020-09-01 09:17 UTC, Moskize91 commented on golang/token.go
> +// SDKToken 生成 sdk token
```golang
SDKToken(accessKey string, secretAccessKey string, lifespan int64, content map[string]string)
```

这个签名中 content 其实是可以确定的，不要用 map 类型。
golang 是可以限制住类型的，我们完全可以定义类型来限制用户输入。

2020-09-01 13:23 UTC, BlackHole1 commented on golang/token.go
> +// SDKToken 生成 sdk token
已完善: https://github.com/netless-io/netless-token/pull/3/commits/f44db69d4f4834a310c681005acac6ba8aaaea26

2020-09-02 01:07 UTC, Moskize91 approved these changes

2020-09-02 01:07 UTC, merged